---
title: "First Knit"
author: "Michael Recinos"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     

I had attended High school at Lancaster High School. yes I graduated from there and I was part of the class of 22. Math and English both have there ups and down and there hard from easy and for my self I been finding English easier for me. I find discovering new word fun and helps me gain more knowledge.

## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   

I have a windows and a macbook at home. I would rate my self at a 4 or 5. yes I have internet connection. My internet is great and rarely has and drop speed.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
Michael is fine but if mike is easier that is fine as well. If you want to use Michael that is fine.

## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
I want to get generation wealth before I pass. I feel like any history would be a bug interest for me. At the moment I am trying to uptain a master degree in radiology.

## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
I had traveled to el Salvador for Christmas to see some family and get out of the cold. no i haven’t but i will be joinning the AMED program through the army after i uptain my master degree.

## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




